targetexist := $(shell if [ -d "$(ANDROID_PRODUCT_OUT)" ]; then echo "exist"; else echo "notexist"; fi;)
ifneq ($(targetexist), exist)
VROOT		:= $(MDIR)/../buildroot/output/target
else
VROOT		:= $(ANDROID_PRODUCT_OUT)/sprdisk/target
endif

include $(VROOT)/../build/utest.config

CC		:= $(CROSS_COMPILE)gcc
CPP		:= $(CROSS_COMPILE)g++
LD		:= $(CROSS_COMPILE)ld
AR		:= $(CROSS_COMPILE)ar
STRIP		:= $(CROSS_COMPILE)strip
RANLIB		:= $(CROSS_COMPILE)ranlib
CFLAGS		:= -Wall -Os
CPPFLAGS	:= -Wall
LDFLAGS		:= -L$(VROOT)/usr/lib

.PHONY: build install clean

