LOCAL_PATH:= $(call my-dir)
ifeq ($(strip $(FOTA_DL_SUPPORT)), true)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := DlSystemFota
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
#LOCAL_CERTIFICATE := PRESIGNED
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := app/DlSystemFota.apk
LOCAL_PREBUILT_JNI_LIBS:= \
	app/lib/armeabi-v7a/libkey.so
include $(BUILD_PREBUILT)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := DlSystemUpdate
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := app/DlSystemUpdate.apk
include $(BUILD_PREBUILT)
endif


