package com.android.internal.telephony;

public class ImsRILConstants {

    final static int RIL_SPRD_REQUEST_BASE = 5002;

    final static int RIL_REQUEST_GET_IMS_CURRENT_CALLS = RIL_SPRD_REQUEST_BASE + 1;
    final static int RIL_REQUEST_SET_IMS_VOICE_CALL_AVAILABILITY = RIL_SPRD_REQUEST_BASE + 2;
    final static int RIL_REQUEST_GET_IMS_VOICE_CALL_AVAILABILITY = RIL_SPRD_REQUEST_BASE + 3;
    final static int RIL_REQUEST_INIT_ISIM = RIL_SPRD_REQUEST_BASE + 4;
    final static int RIL_REQUEST_REGISTER_IMS_IMPU = RIL_SPRD_REQUEST_BASE + 5;
    final static int RIL_REQUEST_REGISTER_IMS_IMPI = RIL_SPRD_REQUEST_BASE + 6;
    final static int RIL_REQUEST_REGISTER_IMS_DOMAIN = RIL_SPRD_REQUEST_BASE + 7;
    final static int RIL_REQUEST_ENABLE_IMS = RIL_SPRD_REQUEST_BASE + 8;
    final static int RIL_REQUEST_DISABLE_IMS = RIL_SPRD_REQUEST_BASE + 9;
    final static int RIL_REQUEST_REGISTER_IMS_IMEI = RIL_SPRD_REQUEST_BASE + 10;
    final static int RIL_REQUEST_IMS_CALL_REQUEST_MEDIA_CHANGE  = RIL_SPRD_REQUEST_BASE + 11;
    final static int RIL_REQUEST_IMS_CALL_RESPONSE_MEDIA_CHANGE = RIL_SPRD_REQUEST_BASE + 12;
    final static int RIL_REQUEST_REGISTER_IMS_XCAP = RIL_SPRD_REQUEST_BASE + 13;
    final static int RIL_REQUEST_REGISTER_IMS_BSF = RIL_SPRD_REQUEST_BASE + 14;
    final static int RIL_REQUEST_SET_IMS_SMSC = RIL_SPRD_REQUEST_BASE + 15;
    final static int RIL_REQUEST_IMS_CALL_FALL_BACK_TO_VOICE = RIL_SPRD_REQUEST_BASE + 16;
    final static int RIL_REQUEST_SET_IMS_INITIAL_ATTACH_APN = RIL_SPRD_REQUEST_BASE + 17;
    final static int RIL_REQUEST_QUERY_CALL_FORWARD_STATUS_URI = RIL_SPRD_REQUEST_BASE + 18;
    final static int RIL_REQUEST_SET_CALL_FORWARD_URI = RIL_SPRD_REQUEST_BASE + 19;
    final static int RIL_REQUEST_IMS_INITIAL_GROUP_CALL = RIL_SPRD_REQUEST_BASE + 20;
    final static int RIL_REQUEST_IMS_ADD_TO_GROUP_CALL = RIL_SPRD_REQUEST_BASE + 21;
    final static int RIL_REQUEST_IMS_SET_CONFERENCE_URI = RIL_SPRD_REQUEST_BASE + 22;

    final static int RIL_SPRD_UNSOL_RESPONSE_BASE = 6000;

    final static int RIL_UNSOL_RESPONSE_IMS_CALL_STATE_CHANGED = RIL_SPRD_UNSOL_RESPONSE_BASE +23;
    final static int RIL_UNSOL_RESPONS_IMS_CONN_ENABLE = RIL_SPRD_UNSOL_RESPONSE_BASE +25;
}
