#!/bin/sh
#
# Start mdev....
#

case "$1" in
  start)
	echo "Starting adbd..."
	/usr/bin/adbd &
	/usr/bin/serialno
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
