# ext4 partition layout
# ext4 partition layout
TARGET_USERIMAGES_USE_EXT4 := true
ifeq ($(STORAGE_INTERNAL), physical)
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1500000000
else
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2800000000
endif
BOARD_CACHEIMAGE_PARTITION_SIZE := 150000000
BOARD_PRODNVIMAGE_PARTITION_SIZE := 5242880
BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODNVIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PERSISTIMAGE_PARTITION_SIZE := 2097152

TARGET_SYSTEMIMAGES_SPARSE_EXT_DISABLED := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false
TARGET_CACHEIMAGES_SPARSE_EXT_DISABLED := false
TARGET_PRODNVIMAGES_SPARSE_EXT_DISABLED := true

#copy partition info xml
#PRODUCT_COPY_FILES += $(BOARDDIR)/tshark3_t2.xml:$(PRODUCT_OUT)/tshark3_t2.xml
#PRODUCT_COPY_FILES += $(BOARDDIR)/tshark3_fpga.xml:$(PRODUCT_OUT)/tshark3_fpga.xml
PRODUCT_COPY_FILES += $(BOARDDIR)/tshark3.xml:$(PRODUCT_OUT)/tshark3.xml
#PRODUCT_COPY_FILES += $(BOARDDIR)/pike.xml:$(PRODUCT_OUT)/pike.xml
#PRODUCT_COPY_FILES += $(BOARDDIR)/tshark2.xml:$(PRODUCT_OUT)/tshark2.xml
